# Generated by Django 2.2.1 on 2019-05-12 18:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.datetime


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255)),
                ('task_arguments', django.contrib.postgres.fields.jsonb.JSONField()),
                ('queue', models.CharField(max_length=255)),
                ('run_at', models.DateTimeField(default=django.db.models.functions.datetime.Now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('result', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_expression', models.CharField(max_length=128)),
                ('timezone', models.CharField(default='America/Chicago', max_length=128)),
                ('is_enabled', models.BooleanField(default=False)),
                ('task_name', models.CharField(max_length=255)),
                ('task_arguments', django.contrib.postgres.fields.jsonb.JSONField()),
                ('queue', models.CharField(max_length=255)),
                ('next_task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.Task')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='from_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tasks.TaskSchedule'),
        ),
        migrations.AddConstraint(
            model_name='taskschedule',
            constraint=models.CheckConstraint(check=models.Q(models.Q(models.Q(('is_enabled', True), ('next_task__isnull', False)), models.Q(('is_enabled', False), ('next_task__isnull', True)), _connector='OR')), name='enabled_task_require_next_task'),
        ),
        migrations.AddConstraint(
            model_name='taskschedule',
            constraint=models.CheckConstraint(check=models.Q(task_arguments__typeof='object'), name='task_arguments_must_be_object'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(check=models.Q(task_arguments__typeof='object'), name='task_arguments_must_be_object'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(condition=models.Q(from_schedule__isnull=False), fields=('from_schedule', 'run_at'), name='no_duplicate_scheduled_tasks'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(condition=models.Q(('from_schedule__isnull', False), ('started_at__isnull', True)), fields=('from_schedule',), name='only_one_pending_task_from_schedule'),
        ),
    ]
