# Generated by Django 2.2.1 on 2019-05-12 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='queue',
            field=models.CharField(default='default', max_length=255),
        ),
    ]
